### ISSUE TITLE
name update for groove

### ISSUE THREAD

**Issue by JoeD80** [travisboss/absolutely_right_pac#1]
Here's what I see
![image](https://user-images.githubusercontent.com/36645894/113621403-31e35000-9621-11eb-9e76-003557c01a8f.png)

Here's what Groove pages needs to import
<meta name="gp-ownership-proof" content="5fff5f9ae2ec29006f5d30ee">

**Comment by travisboss** [comment]
@JoeD80 I do not see what Groove pages needs to import, but if you'll notice the third line of `data-react-helmet` that is the import you are looking for?

<img width="678" alt="Screen Shot 2021-04-06 at 8 23 08 AM" src="https://user-images.githubusercontent.com/16948721/113717538-54bd4500-96b1-11eb-94ce-b8d17b912e09.png">
